/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.controladorAvion;
import controlador.controladorListados;
import controlador.controladorPiloto;
import controlador.controladorProyectoBase;
import java.awt.event.ItemEvent;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import modelo.vo.Avion;
import modelo.vo.Usuario;

/**
 *
 * @author Acceso a datos
 */
public class ProyectoBase extends javax.swing.JFrame {

    public static Usuario usuarioActual;
    public static Avion avionActual;

    /**
     * Creates new form ProyectoBase
     */
    public ProyectoBase() {
        initComponents();
        controladorProyectoBase.iniciaBD();
        controladorProyectoBase.recargarRelacionesManualmente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameIniciado = new javax.swing.JFrame();
        txtNomPiloto = new javax.swing.JTextField();
        btnModifPiloto = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnBorrarPiloto = new javax.swing.JButton();
        txtApellPiloto = new javax.swing.JTextField();
        btnTodosPilotoAvion = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ckMilitar = new javax.swing.JCheckBox();
        txtFechaNacimiento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtAvionNombre = new javax.swing.JLabel();
        ckPsicologo = new javax.swing.JCheckBox();
        txtDNIPiloto = new javax.swing.JTextField();
        spNumHijos = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtHorasVuelo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNacionalidad = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnInsertarPiloto = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        cbAvion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cbOrigenVuelo = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        cbDestinoVuelo = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDetallesVuelo = new javax.swing.JTextArea();
        txtNumvuelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNPasajeros = new javax.swing.JTextField();
        btnLimpiarCampos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lbSaludo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnNuevoAvion = new javax.swing.JButton();
        btnMostrarListados = new javax.swing.JButton();
        FrameListados = new javax.swing.JFrame();
        btnListado1 = new javax.swing.JButton();
        btnListado2 = new javax.swing.JButton();
        btnListado3 = new javax.swing.JButton();
        txtMinimoHVuelo = new javax.swing.JTextField();
        txtxMinPasaj = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaListados = new javax.swing.JTable();
        txtListNaci = new javax.swing.JTextField();
        ckListadoMilitar = new javax.swing.JCheckBox();
        cbDestinoListado = new javax.swing.JComboBox<>();
        ckListadoPsicologo = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        FrameGestionUser = new javax.swing.JFrame();
        jLabel21 = new javax.swing.JLabel();
        txtGestionNombre = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtGestionPass = new javax.swing.JPasswordField();
        btnAlta = new javax.swing.JButton();
        btnBajaUser = new javax.swing.JButton();
        btnIniciarBBDD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreUser = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();

        txtNomPiloto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomPilotoFocusLost(evt);
            }
        });

        btnModifPiloto.setText("Modificar");
        btnModifPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifPilotoActionPerformed(evt);
            }
        });

        jLabel12.setText("Hijos");

        btnBorrarPiloto.setText("Borrar");
        btnBorrarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarPilotoActionPerformed(evt);
            }
        });

        btnTodosPilotoAvion.setText("Ver todos pilotos asociados a este avion");
        btnTodosPilotoAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosPilotoAvionActionPerformed(evt);
            }
        });

        jLabel13.setText("Apellido");

        txtFechaNacimiento.setText("aaaa-mm-dd");

        jLabel10.setText("Fue militar");

        jLabel14.setText("Fecha nacimiento");

        txtAvionNombre.setText("Avion ");

        txtDNIPiloto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDNIPilotoFocusLost(evt);
            }
        });

        spNumHijos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel16.setText("DNI");

        jLabel15.setText("Nacionalidad");

        jLabel9.setText("Psicologo");

        jLabel17.setText("Horas Vuelo");

        jLabel11.setText("Nombre Piloto");

        btnInsertarPiloto.setText("Insertar");
        btnInsertarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarPilotoActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cbAvion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAvionItemStateChanged(evt);
            }
        });
        cbAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAvionActionPerformed(evt);
            }
        });

        jLabel7.setText("Destino");

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbOrigenVuelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madrid", "Barcelona", "Paris", "New York", "Pekin", "Moscu", "Casablanca", "Medellin", "Berlin", "Brasilia", "Buenos Aires", "Roma", "Lima", " " }));

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbDestinoVuelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madrid", "Barcelona", "Paris", "New York", "Pekin", "Moscu", "Casablanca", "Medellin", "Berlin", "Brasilia", "Buenos Aires", "Roma", "Lima", " " }));
        cbDestinoVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDestinoVueloActionPerformed(evt);
            }
        });

        jButton4.setText("Borrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Detalles");

        jLabel3.setText("Numero de Vuelo");

        taDetallesVuelo.setColumns(20);
        taDetallesVuelo.setRows(5);
        jScrollPane1.setViewportView(taDetallesVuelo);

        jLabel4.setText("Origen");

        btnLimpiarCampos.setText("Limpiar Campos");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        jLabel5.setText("Nº Pasajeros");

        txtFecha.setText("2025-12-12 22:22:22");

        lbSaludo.setText("Hola");

        jLabel6.setText("Fecha");

        btnNuevoAvion.setText("Nuevo");
        btnNuevoAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAvionActionPerformed(evt);
            }
        });

        btnMostrarListados.setText("Mostrar Listados");
        btnMostrarListados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarListadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameIniciadoLayout = new javax.swing.GroupLayout(FrameIniciado.getContentPane());
        FrameIniciado.getContentPane().setLayout(FrameIniciadoLayout);
        FrameIniciadoLayout.setHorizontalGroup(
            FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameIniciadoLayout.createSequentialGroup()
                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameIniciadoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameIniciadoLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lbSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FrameIniciadoLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNumvuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(FrameIniciadoLayout.createSequentialGroup()
                                        .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(txtNPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)
                                            .addComponent(cbOrigenVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(FrameIniciadoLayout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(cbDestinoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(FrameIniciadoLayout.createSequentialGroup()
                                        .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(FrameIniciadoLayout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(276, 276, 276))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jButton1))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(FrameIniciadoLayout.createSequentialGroup()
                                    .addComponent(btnNuevoAvion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton4))
                                .addComponent(cbAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(FrameIniciadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLimpiarCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addGroup(FrameIniciadoLayout.createSequentialGroup()
                        .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FrameIniciadoLayout.createSequentialGroup()
                                .addComponent(btnInsertarPiloto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMostrarListados)
                                    .addComponent(btnModifPiloto))))
                        .addGap(63, 63, 63)
                        .addComponent(btnBorrarPiloto))
                    .addComponent(btnTodosPilotoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FrameIniciadoLayout.createSequentialGroup()
                        .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtNomPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addComponent(txtApellPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtAvionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtDNIPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FrameIniciadoLayout.createSequentialGroup()
                        .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameIniciadoLayout.createSequentialGroup()
                                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(spNumHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81)
                                .addComponent(jLabel9))
                            .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(FrameIniciadoLayout.createSequentialGroup()
                                .addComponent(ckPsicologo)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckMilitar))
                            .addComponent(txtHorasVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        FrameIniciadoLayout.setVerticalGroup(
            FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameIniciadoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtAvionNombre)
                .addGap(27, 27, 27)
                .addComponent(btnTodosPilotoAvion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(txtDNIPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FrameIniciadoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameIniciadoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorasVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameIniciadoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spNumHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(ckPsicologo)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ckMilitar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(36, 36, 36)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarPiloto)
                    .addComponent(btnModifPiloto)
                    .addComponent(btnBorrarPiloto))
                .addGap(89, 89, 89)
                .addComponent(btnMostrarListados)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameIniciadoLayout.createSequentialGroup()
                .addComponent(lbSaludo)
                .addGap(31, 31, 31)
                .addComponent(cbAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(btnNuevoAvion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtNumvuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FrameIniciadoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbOrigenVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FrameIniciadoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cbDestinoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrameIniciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(142, 142, 142)
                .addComponent(btnLimpiarCampos)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameIniciadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
        );

        btnListado1.setText("Listado1");
        btnListado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListado1ActionPerformed(evt);
            }
        });

        btnListado2.setText("Listado2");
        btnListado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListado2ActionPerformed(evt);
            }
        });

        btnListado3.setText("Listado3");
        btnListado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListado3ActionPerformed(evt);
            }
        });

        tablaListados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaListados);

        ckListadoMilitar.setText("Militar");

        cbDestinoListado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madrid", "Barcelona", "Paris", "New York", "Pekin", "Moscu", "Casablanca", "Medellin", "Berlin", "Brasilia", "Buenos Aires", "Roma", "Lima", " " }));

        ckListadoPsicologo.setText("Psicologo");

        jLabel18.setText("Horas Vuelo min.");

        jLabel19.setText("nº Pasajeros min.");

        jLabel20.setText("Nacionalidad");

        javax.swing.GroupLayout FrameListadosLayout = new javax.swing.GroupLayout(FrameListados.getContentPane());
        FrameListados.getContentPane().setLayout(FrameListadosLayout);
        FrameListadosLayout.setHorizontalGroup(
            FrameListadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameListadosLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(FrameListadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameListadosLayout.createSequentialGroup()
                        .addGroup(FrameListadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameListadosLayout.createSequentialGroup()
                                .addGroup(FrameListadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FrameListadosLayout.createSequentialGroup()
                                        .addComponent(txtMinimoHVuelo)
                                        .addGap(14, 14, 14)
                                        .addComponent(ckListadoMilitar))
                                    .addComponent(btnListado1))
                                .addGap(95, 95, 95)
                                .addGroup(FrameListadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnListado2)
                                    .addGroup(FrameListadosLayout.createSequentialGroup()
                                        .addGroup(FrameListadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtxMinPasaj)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(24, 24, 24)
                                        .addComponent(cbDestinoListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(FrameListadosLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(437, 437, 437)))
                        .addGap(57, 57, 57)
                        .addGroup(FrameListadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameListadosLayout.createSequentialGroup()
                                .addComponent(txtListNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ckListadoPsicologo))
                            .addComponent(btnListado3)
                            .addComponent(jLabel20))))
                .addGap(46, 46, 46))
        );
        FrameListadosLayout.setVerticalGroup(
            FrameListadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameListadosLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(FrameListadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameListadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMinimoHVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtListNaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckListadoMilitar)
                    .addComponent(txtxMinPasaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDestinoListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckListadoPsicologo))
                .addGap(30, 30, 30)
                .addGroup(FrameListadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListado1)
                    .addComponent(btnListado2)
                    .addComponent(btnListado3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jLabel21.setText("Nombre");

        jLabel22.setText("Contraseña");

        btnAlta.setText("Alta");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        btnBajaUser.setText("Dar de baja al usuario actual");
        btnBajaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameGestionUserLayout = new javax.swing.GroupLayout(FrameGestionUser.getContentPane());
        FrameGestionUser.getContentPane().setLayout(FrameGestionUserLayout);
        FrameGestionUserLayout.setHorizontalGroup(
            FrameGestionUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameGestionUserLayout.createSequentialGroup()
                .addGroup(FrameGestionUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameGestionUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FrameGestionUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAlta)
                            .addGroup(FrameGestionUserLayout.createSequentialGroup()
                                .addGroup(FrameGestionUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(txtGestionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(95, 95, 95)
                                .addGroup(FrameGestionUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(txtGestionPass, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(FrameGestionUserLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnBajaUser)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        FrameGestionUserLayout.setVerticalGroup(
            FrameGestionUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameGestionUserLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(FrameGestionUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(FrameGestionUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGestionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGestionPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnAlta)
                .addGap(37, 37, 37)
                .addComponent(btnBajaUser)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnIniciarBBDD.setText("Iniciar BBDD");
        btnIniciarBBDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarBBDDActionPerformed(evt);
            }
        });

        jLabel1.setText("nombre");

        jLabel2.setText("contraseña");

        jButton2.setText("Entrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnUsuarios.setText("Gestionar Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIniciarBBDD)
                                    .addComponent(txtNombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPass)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addComponent(btnUsuarios)
                        .addGap(109, 109, 109))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnIniciarBBDD)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnUsuarios))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        controladorProyectoBase.cerrarBD();
    }//GEN-LAST:event_formWindowClosed

    private void btnIniciarBBDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarBBDDActionPerformed
        controladorProyectoBase.iniciarDatos();
    }//GEN-LAST:event_btnIniciarBBDDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        usuarioActual = controladorProyectoBase.autenticar();


    }//GEN-LAST:event_jButton2ActionPerformed

    public JFrame getFrameIniciado() {
        return FrameIniciado;
    }

    public void setFrameIniciado(JFrame FrameIniciado) {
        this.FrameIniciado = FrameIniciado;
    }

    public JPasswordField getTxtPass() {
        return txtPass;
    }

    public void setTxtPass(JPasswordField txtPass) {
        this.txtPass = txtPass;
    }

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtNomPilotoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomPilotoFocusLost

    }//GEN-LAST:event_txtNomPilotoFocusLost

    private void btnModifPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifPilotoActionPerformed
        controladorPiloto.modificarPiloto();
    }//GEN-LAST:event_btnModifPilotoActionPerformed

    private void btnBorrarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarPilotoActionPerformed
        controladorPiloto.borrarPiloto();
    }//GEN-LAST:event_btnBorrarPilotoActionPerformed

    private void btnTodosPilotoAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosPilotoAvionActionPerformed
        controladorPiloto.verPilotosporAvion();
    }//GEN-LAST:event_btnTodosPilotoAvionActionPerformed

    private void txtDNIPilotoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDNIPilotoFocusLost
        controladorPiloto.cargarPiloto();
    }//GEN-LAST:event_txtDNIPilotoFocusLost

    private void btnInsertarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarPilotoActionPerformed
        controladorPiloto.insertarPiloto();
    }//GEN-LAST:event_btnInsertarPilotoActionPerformed

    private void cbAvionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAvionItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Avion a = (Avion) getCbAvion().getSelectedItem();

            // Guardar el avión seleccionado en el controlador
            controladorProyectoBase.setAvionSeleccionado(a);

            // Cargar datos o limpiar campos
            if (a != null) {
                controladorAvion.cargarDatosAvion();
            } else {
                // Si es null, limpia los campos
                getTxtNumvuelo().setText("");
                getTxtNPasajeros().setText("");
                getTxtFecha().setText("");
                getTaDetallesVuelo().setText("");
                getCbOrigenVuelo().setSelectedIndex(-1);
                getCbDestinoVuelo().setSelectedIndex(-1);
            }

        }
    }//GEN-LAST:event_cbAvionItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controladorAvion.insertarVuelo(usuarioActual);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        controladorAvion.modificarAvion(usuarioActual);
    }//GEN-LAST:event_jButton3ActionPerformed

    public JButton getBtnListado1() {
        return btnListado1;
    }

    public void setBtnListado1(JButton btnListado1) {
        this.btnListado1 = btnListado1;
    }

    public JButton getBtnListado2() {
        return btnListado2;
    }

    public void setBtnListado2(JButton btnListado2) {
        this.btnListado2 = btnListado2;
    }

    public JButton getBtnListado3() {
        return btnListado3;
    }

    public void setBtnListado3(JButton btnListado3) {
        this.btnListado3 = btnListado3;
    }

    public JTable getTablaListados() {
        return tablaListados;
    }

    public void setTablaListados(JTable tablaListados) {
        this.tablaListados = tablaListados;
    }

    public JComboBox<String> getCbDestinoListado() {
        return cbDestinoListado;
    }

    public void setCbDestinoListado(JComboBox<String> cbDestinoListado) {
        this.cbDestinoListado = cbDestinoListado;
    }

    public JTextField getTxtListNaci() {
        return txtListNaci;
    }

    public void setTxtListNaci(JTextField txtListNaci) {
        this.txtListNaci = txtListNaci;
    }

    public JTextField getTxtMinimoHVuelo() {
        return txtMinimoHVuelo;
    }

    public void setTxtMinimoHVuelo(JTextField txtMinimoHVuelo) {
        this.txtMinimoHVuelo = txtMinimoHVuelo;
    }

    public JTextField getTxtxMinPasaj() {
        return txtxMinPasaj;
    }

    public void setTxtxMinPasaj(JTextField txtxMinPasaj) {
        this.txtxMinPasaj = txtxMinPasaj;
    }


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        controladorAvion.borrarAvion();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        controladorProyectoBase.limpiarCampos();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void cbAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAvionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAvionActionPerformed

    private void btnNuevoAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAvionActionPerformed
        controladorProyectoBase.prepararNuevoAvion();
    }//GEN-LAST:event_btnNuevoAvionActionPerformed

    private void btnMostrarListadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarListadosActionPerformed
        FrameListados.setVisible(true);
        FrameListados.setSize(950, 950);
    }//GEN-LAST:event_btnMostrarListadosActionPerformed

    private void btnListado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListado1ActionPerformed
        String param1 = getTxtMinimoHVuelo().getText().trim();
        String param2 = getCkListadoMilitar().isSelected() ? "true" : "false";

        controladorListados.ejecutarListado1(
                param1,
                param2,
                getTablaListados(),
                usuarioActual
        );

    }//GEN-LAST:event_btnListado1ActionPerformed

    private void btnListado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListado2ActionPerformed
        String param1 = getTxtxMinPasaj().getText().trim();
        String param2 = getCbDestinoListado().getSelectedItem().toString().trim();

        controladorListados.ejecutarListado2(
                param1,
                param2,
                getTablaListados(),
                usuarioActual
        );
    }//GEN-LAST:event_btnListado2ActionPerformed

    private void btnListado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListado3ActionPerformed
        String param1 = getTxtListNaci().getText().trim();
        String param2 = getCkListadoPsicologo().isSelected() ? "true" : "false";

        controladorListados.ejecutarListado3(
                param1,
                param2,
                getTablaListados(),
                usuarioActual
        );
    }//GEN-LAST:event_btnListado3ActionPerformed

    private void cbDestinoVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDestinoVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDestinoVueloActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        FrameGestionUser.setVisible(true);
        FrameGestionUser.setSize(500, 500);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnBajaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaUserActionPerformed
        controladorProyectoBase.darBaja();
    }//GEN-LAST:event_btnBajaUserActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        controladorProyectoBase.darAlta();
    }//GEN-LAST:event_btnAltaActionPerformed

    public JButton getBtnTodosPilotoAvion() {
        return btnTodosPilotoAvion;
    }

    public void setBtnTodosPilotoAvion(JButton btnTodosPilotoAvion) {
        this.btnTodosPilotoAvion = btnTodosPilotoAvion;
    }

    public JCheckBox getCkMilitar() {
        return ckMilitar;
    }

    public JTextField getTxtDNIPiloto() {
        return txtDNIPiloto;
    }

    public JFrame getFrameGestionUser() {
        return FrameGestionUser;
    }

    public void setFrameGestionUser(JFrame FrameGestionUser) {
        this.FrameGestionUser = FrameGestionUser;
    }

    public JButton getBtnAlta() {
        return btnAlta;
    }

    public void setBtnAlta(JButton btnAlta) {
        this.btnAlta = btnAlta;
    }

    public JButton getBtnBajaUser() {
        return btnBajaUser;
    }

    public void setBtnBajaUser(JButton btnBajaUser) {
        this.btnBajaUser = btnBajaUser;
    }

    public JCheckBox getCkListadoMilitar() {
        return ckListadoMilitar;
    }

    public void setCkListadoMilitar(JCheckBox ckListadoMilitar) {
        this.ckListadoMilitar = ckListadoMilitar;
    }

    public JCheckBox getCkListadoPsicologo() {
        return ckListadoPsicologo;
    }

    public void setCkListadoPsicologo(JCheckBox ckListadoPsicologo) {
        this.ckListadoPsicologo = ckListadoPsicologo;
    }

    public JTextField getTxtGestionNombre() {
        return txtGestionNombre;
    }

    public void setTxtGestionNombre(JTextField txtGestionNombre) {
        this.txtGestionNombre = txtGestionNombre;
    }

    public JPasswordField getTxtGestionPass() {
        return txtGestionPass;
    }

    public void setTxtGestionPass(JPasswordField txtGestionPass) {
        this.txtGestionPass = txtGestionPass;
    }

    public void setCkMilitar(JCheckBox ckMilitar) {
        this.ckMilitar = ckMilitar;
    }

    public JCheckBox getCkPsicologo() {
        return ckPsicologo;
    }

    public void setCkPsicologo(JCheckBox ckPsicologo) {
        this.ckPsicologo = ckPsicologo;
    }

    public JLabel getTxtAvionNombre() {
        return txtAvionNombre;
    }

    public void setTxtAvionNombre(JLabel txtAvionNombre) {
        this.txtAvionNombre = txtAvionNombre;
    }

    public static Usuario getUsuarioActual() {
        return usuarioActual;
    }

    public static void setUsuarioActual(Usuario usuarioActual) {
        ProyectoBase.usuarioActual = usuarioActual;
    }

    public JButton getBtnBorrarPiloto() {
        return btnBorrarPiloto;
    }

    public void setBtnBorrarPiloto(JButton btnBorrarPiloto) {
        this.btnBorrarPiloto = btnBorrarPiloto;
    }

    public JButton getBtnIniciarBBDD() {
        return btnIniciarBBDD;
    }

    public void setBtnIniciarBBDD(JButton btnIniciarBBDD) {
        this.btnIniciarBBDD = btnIniciarBBDD;
    }

    public JButton getBtnInsertarPiloto() {
        return btnInsertarPiloto;
    }

    public void setBtnInsertarPiloto(JButton btnInsertarPiloto) {
        this.btnInsertarPiloto = btnInsertarPiloto;
    }

    public JButton getBtnModifPiloto() {
        return btnModifPiloto;
    }

    public void setBtnModifPiloto(JButton btnModifPiloto) {
        this.btnModifPiloto = btnModifPiloto;
    }

    public JButton getBtnTododPilotos() {
        return btnTodosPilotoAvion;
    }

    public void setBtnTododPilotos(JButton btnTododPilotos) {
        this.btnTodosPilotoAvion = btnTododPilotos;
    }

    public JButton getBtnUsuarios() {
        return btnUsuarios;
    }

    public void setBtnUsuarios(JButton btnUsuarios) {
        this.btnUsuarios = btnUsuarios;
    }

    public JCheckBox getCkAntecedentes() {
        return ckPsicologo;
    }

    public JFrame getFrameListados() {
        return FrameListados;
    }

    public void setFrameListados(JFrame FrameListados) {
        this.FrameListados = FrameListados;
    }

    public JButton getBtnMostrarListados() {
        return btnMostrarListados;
    }

    public void setBtnMostrarListados(JButton btnMostrarListados) {
        this.btnMostrarListados = btnMostrarListados;
    }

    public void setCkAntecedentes(JCheckBox ckAntecedentes) {
        this.ckPsicologo = ckAntecedentes;
    }

    public JSpinner getSpNumHijos() {
        return spNumHijos;
    }

    public void setSpNumHijos(JSpinner spNumHijos) {
        this.spNumHijos = spNumHijos;
    }

    public JTextField getTxtApellPiloto() {
        return txtApellPiloto;
    }

    public void setTxtApellPiloto(JTextField txtApellPiloto) {
        this.txtApellPiloto = txtApellPiloto;
    }

    public JTextField getTxtFechaNacimiento() {
        return txtFechaNacimiento;
    }

    public void setTxtFechaNacimiento(JTextField txtFechaNacimiento) {
        this.txtFechaNacimiento = txtFechaNacimiento;
    }

    public JTextField getTxtNacionalidad() {
        return txtNacionalidad;
    }

    public void setTxtNacionalidad(JTextField txtNacionalidad) {
        this.txtNacionalidad = txtNacionalidad;
    }

    public JTextField getTxtNomPiloto() {
        return txtNomPiloto;
    }

    public void setTxtNomPiloto(JTextField txtNomPiloto) {
        this.txtNomPiloto = txtNomPiloto;
    }

    public JTextField getTxtFecha() {
        return txtFecha;
    }

    public JTextField getTxtNPasajeros() {
        return txtNPasajeros;
    }

    public JButton getBtnAccederPiloto() {
        return btnLimpiarCampos;
    }

    public JComboBox<Avion> getCbAvion() {
        return cbAvion;
    }

    public JComboBox<String> getCbDestinoVuelo() {
        return cbDestinoVuelo;
    }

    public JComboBox<String> getCbOrigenVuelo() {
        return cbOrigenVuelo;
    }

    public JTextArea getTaDetallesVuelo() {
        return taDetallesVuelo;
    }

    public JTextField getTxtNumvuelo() {
        return txtNumvuelo;
    }

    public JTextField getTxtNombreUser() {
        return txtNombreUser;
    }

    public JLabel getLbSaludo() {
        return lbSaludo;
    }

    public JTextField getTxtHorasVuelo() {
        return txtHorasVuelo;
    }

    public void setTxtHorasVuelo(JTextField txtHorasVuelo) {
        this.txtHorasVuelo = txtHorasVuelo;
    }

    public JButton getBtnLimpiarCampos() {
        return btnLimpiarCampos;
    }

    public void setBtnLimpiarCampos(JButton btnLimpiarCampos) {
        this.btnLimpiarCampos = btnLimpiarCampos;
    }

    public JButton getBtnNuevoAvion() {
        return btnNuevoAvion;
    }

    public void setBtnNuevoAvion(JButton btnNuevoAvion) {
        this.btnNuevoAvion = btnNuevoAvion;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameGestionUser;
    private javax.swing.JFrame FrameIniciado;
    private javax.swing.JFrame FrameListados;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBajaUser;
    private javax.swing.JButton btnBorrarPiloto;
    private javax.swing.JButton btnIniciarBBDD;
    private javax.swing.JButton btnInsertarPiloto;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnListado1;
    private javax.swing.JButton btnListado2;
    private javax.swing.JButton btnListado3;
    private javax.swing.JButton btnModifPiloto;
    private javax.swing.JButton btnMostrarListados;
    private javax.swing.JButton btnNuevoAvion;
    private javax.swing.JButton btnTodosPilotoAvion;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JComboBox<Avion> cbAvion;
    private javax.swing.JComboBox<String> cbDestinoListado;
    private javax.swing.JComboBox<String> cbDestinoVuelo;
    private javax.swing.JComboBox<String> cbOrigenVuelo;
    private javax.swing.JCheckBox ckListadoMilitar;
    private javax.swing.JCheckBox ckListadoPsicologo;
    private javax.swing.JCheckBox ckMilitar;
    private javax.swing.JCheckBox ckPsicologo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbSaludo;
    private javax.swing.JSpinner spNumHijos;
    private javax.swing.JTextArea taDetallesVuelo;
    private javax.swing.JTable tablaListados;
    private javax.swing.JTextField txtApellPiloto;
    private javax.swing.JLabel txtAvionNombre;
    private javax.swing.JTextField txtDNIPiloto;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtGestionNombre;
    private javax.swing.JPasswordField txtGestionPass;
    private javax.swing.JTextField txtHorasVuelo;
    private javax.swing.JTextField txtListNaci;
    private javax.swing.JTextField txtMinimoHVuelo;
    private javax.swing.JTextField txtNPasajeros;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNomPiloto;
    private javax.swing.JTextField txtNombreUser;
    private javax.swing.JTextField txtNumvuelo;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtxMinPasaj;
    // End of variables declaration//GEN-END:variables
}
